# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vm_control_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VMController(object):
    def setupUi(self, VMController):
        VMController.setObjectName("VMController")
        VMController.setWindowModality(QtCore.Qt.ApplicationModal)
        VMController.resize(1024, 600)
        VMController.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.Main = QtWidgets.QWidget(VMController)
        self.Main.setEnabled(True)
        self.Main.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Main.setObjectName("Main")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Main)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 30, 370, 454))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Mira_Layer = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Mira_Layer.setContentsMargins(10, 10, 10, 10)
        self.Mira_Layer.setObjectName("Mira_Layer")
        self.MiraPicture = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.MiraPicture.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.MiraPicture.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MiraPicture.setMidLineWidth(0)
        self.MiraPicture.setText("")
        self.MiraPicture.setTextFormat(QtCore.Qt.PlainText)
        self.MiraPicture.setPixmap(QtGui.QPixmap("./imgs/Mira.png"))
        self.MiraPicture.setScaledContents(False)
        self.MiraPicture.setAlignment(QtCore.Qt.AlignCenter)
        self.MiraPicture.setWordWrap(False)
        self.MiraPicture.setOpenExternalLinks(False)
        self.MiraPicture.setObjectName("MiraPicture")
        self.Mira_Layer.addWidget(self.MiraPicture)
        self.Mira = QtWidgets.QHBoxLayout()
        self.Mira.setObjectName("Mira")
        self.MiReboot = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.MiReboot.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./imgs/reboot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MiReboot.setIcon(icon)
        self.MiReboot.setIconSize(QtCore.QSize(100, 100))
        self.MiReboot.setObjectName("MiReboot")
        self.Mira.addWidget(self.MiReboot)
        self.MiStart = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.MiStart.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./imgs/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MiStart.setIcon(icon1)
        self.MiStart.setIconSize(QtCore.QSize(100, 100))
        self.MiStart.setObjectName("MiStart")
        self.Mira.addWidget(self.MiStart)
        self.MiShutdown = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.MiShutdown.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./imgs/shutdown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MiShutdown.setIcon(icon2)
        self.MiShutdown.setIconSize(QtCore.QSize(100, 100))
        self.MiShutdown.setObjectName("MiShutdown")
        self.Mira.addWidget(self.MiShutdown)
        self.Mira_Layer.addLayout(self.Mira)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Main)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(570, 30, 370, 451))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Mountain_Layer = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Mountain_Layer.setContentsMargins(10, 10, 10, 10)
        self.Mountain_Layer.setObjectName("Mountain_Layer")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap("./imgs/Mountain.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Mountain_Layer.addWidget(self.label)
        self.Mountain = QtWidgets.QHBoxLayout()
        self.Mountain.setObjectName("Mountain")
        self.MoReboot = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.MoReboot.setText("")
        self.MoReboot.setIcon(icon)
        self.MoReboot.setIconSize(QtCore.QSize(100, 100))
        self.MoReboot.setObjectName("MoReboot")
        self.Mountain.addWidget(self.MoReboot)
        self.MoStart = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.MoStart.setText("")
        self.MoStart.setIcon(icon1)
        self.MoStart.setIconSize(QtCore.QSize(100, 100))
        self.MoStart.setObjectName("MoStart")
        self.Mountain.addWidget(self.MoStart)
        self.MoShutdown = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.MoShutdown.setText("")
        self.MoShutdown.setIcon(icon2)
        self.MoShutdown.setIconSize(QtCore.QSize(100, 100))
        self.MoShutdown.setObjectName("MoShutdown")
        self.Mountain.addWidget(self.MoShutdown)
        self.Mountain_Layer.addLayout(self.Mountain)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.Main)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(30, 500, 971, 78))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Texts = QtWidgets.QVBoxLayout()
        self.Texts.setObjectName("Texts")
        self.CPU_Text = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.CPU_Text.setObjectName("CPU_Text")
        self.Texts.addWidget(self.CPU_Text)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Texts.addWidget(self.line)
        self.RAM_Text = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.RAM_Text.setObjectName("RAM_Text")
        self.Texts.addWidget(self.RAM_Text)
        self.horizontalLayout.addLayout(self.Texts)
        self.Bars = QtWidgets.QVBoxLayout()
        self.Bars.setObjectName("Bars")
        self.CPU_Bar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_5)
        self.CPU_Bar.setProperty("value", 24)
        self.CPU_Bar.setObjectName("CPU_Bar")
        self.Bars.addWidget(self.CPU_Bar)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Bars.addWidget(self.line_2)
        self.RAM_Bar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_5)
        self.RAM_Bar.setProperty("value", 24)
        self.RAM_Bar.setObjectName("RAM_Bar")
        self.Bars.addWidget(self.RAM_Bar)
        self.horizontalLayout.addLayout(self.Bars)
        VMController.setCentralWidget(self.Main)

        self.retranslateUi(VMController)
        QtCore.QMetaObject.connectSlotsByName(VMController)

    def retranslateUi(self, VMController):
        _translate = QtCore.QCoreApplication.translate
        VMController.setWindowTitle(_translate("VMController", "VM-Control"))
        self.CPU_Text.setText(_translate("VMController", "CPU (%)"))
        self.RAM_Text.setText(_translate("VMController", "RAM (%)"))
